---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: database
labels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: Helm
annotations:
  meta.helm.sh/release-name: {{ .Release.Name }}
  meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 18.12.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
