---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-charts.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./nfs-subdir-external-provisioner-charts.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
