---
## https://docs.ibracorp.io/authelia/openid-connect/authelia-setup
## https://florianmuller.com/setup-authelia-bare-metal-with-openid-and-cloudflare-tunnel-on-a-hardened-proxmox-lxc-ubuntu-22-04-lts-container

# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: authelia-secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_TOTP_ISSUER: ${SECRET_DOMAIN}
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_WEBAUTHN_DISPLAY_NAME: "Bakernet"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        # AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: &dbHost homecluster-rw.database.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .AUTHELIA_STORAGE_POSTGRES_USERNAME }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .AUTHELIA_STORAGE_POSTGRES_PASSWORD }}"
        AUTHELIA_NOTIFIER_SMTP_ADDRESS: "{{ .SMTP_SERVER }}:{{ .SMTP_TLS_PORT }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .SMTP_SUPERUSER }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .SMTP_SUPERUSER_PASSWORD }}"
        # AUTHELIA_NOTIFIER_SMTP_PORT: "{{ .SMTP_TLS_PORT }}"
        AUTHELIA_NOTIFIER_SMTP_SENDER: "Bakenet Networks <noreply@${SECRET_DOMAIN}>"
        AUTHELIA_NOTIFIER_SMTP_SUBJECT: "[Bakernet] {title}"
        # GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        # MINIFLUX_OAUTH_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        # WEAVE_GITOPS_OAUTH_CLIENT_SECRET: "{{ .WEAVE_GITOPS_OAUTH_CLIENT_SECRET }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET }}"

  dataFrom:
    - extract:
        key: /bakerkubes/authelia
    - extract:
        key: /bakerkubes/cloudnative-pg
    - extract:
        key: /bakerkubes/lldap
    - extract:
        key: /bakerkubes/email
    - extract:
        key: /bakerkubes/immich

---
