---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://lldap.security.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: uid=admin,ou=people,dc=home,dc=arpa
    password: password
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: bakernet_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    host: redis.database.svc.cluster.local
    database_index: 14
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.database.svc.cluster.local
          port: 26379

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: "*.${SECRET_DOMAIN}"
      networks:
        - internal
      policy: bypass
    - domain: "photos.${SECRET_DOMAIN_NAME}"
      policy: two_factor
      subject:
        - "group:baker-admins"
        - "group:baker-users"

default_redirection_url: "https://auth.bakernet.casa"

regulation:
  ## The number of failed login attempts before user is banned. Set it to 0 to disable regulation.
  max_retries: 3

  ## The time range during which the user can attempt login before being banned. The user is banned if the
  ## authentication failed 'max_retries' times in a 'find_time' seconds window. Find Time accepts duration notation.
  ## See: https://www.authelia.com/configuration/prologue/common/#duration-notation-format
  find_time: 2m

  ## The length of time before a banned user can login again. Ban Time accepts duration notation.
  ## See: https://www.authelia.com/configuration/prologue/common/#duration-notation-format
  ban_time: 5m

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true

    clients:
      - id: immich
        description: "Bakernet Photo Archive"
        secret: "$${IMMICH_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 30d
        scopes: ["openid", "profile", "email"]
        redirect_uris: ["https://photos.${SECRET_DOMAIN}/auth/login", "app.immich:/"]
        userinfo_signed_response_alg: none
    #   - id: grafana
    #     description: Grafana
    #     secret: "$${GRAFANA_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     pre_configured_consent_duration: 1y
    #     scopes: ["openid", "profile", "groups", "email"]
    #     redirect_uris: ["https://grafana.devbu.io/login/generic_oauth"]
    #     userinfo_signed_response_alg: none
    #   - id: miniflux
    #     description: Miniflux
    #     secret: "$${MINIFLUX_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     pre_configured_consent_duration: 1y
    #     scopes: ["openid", "profile", "groups", "email"]
    #     redirect_uris: ["https://miniflux.devbu.io/oauth2/oidc/callback"]
    #     userinfo_signed_response_alg: none
    #   - id: weave-gitops
    #     description: Weave GitOps
    #     secret: "$${WEAVE_GITOPS_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     pre_configured_consent_duration: 1y
    #     scopes: ["openid", "profile", "groups", "email"]
    #     redirect_uris: ["https://wego.devbu.io/oauth2/callback"]
    #     userinfo_signing_algorithm: none
