apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:bsXuvRv0sYRS3RzBMyc+647RAUsFHYzJryordNFdY4v7ajc7ekJCXHQ6ocHuBXMxfw4PdmTUdN+fExC26Cua4A7g8XMMmsLXSfg3tXxwmdT1QSMMMMP8DcYQZCL5YQ==,iv:apEf80efUMBagjVVK8ZqqlRZIdApAHmPE/mWnac4POo=,tag:4ZaPd9tTRZTi9MgNlwd4Vg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:6DOe/+3VHk8xmYXkFQ==,iv:gKToOimHuk3bLwfygE/Tz7ECsa6S5SGomh9FEEqro4g=,tag:pkeeZ69bAxvY6TG2jaVGPQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XPmNyUsMuu997X6KLhFEyHLKhC+Izw==,iv:F7mkUSN4k7mTCuYGBj3WtaK3W+ii/k1d5D1hUjvVqYA=,tag:mRoLn+nWYP/TSSgXeljZgg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cM0R5b6xiUz0V1k035NB/1KMvJr/fpPU9MxRzcKT2ikTKQZr,iv:hQZlGbVpusoSlTChxLDuwZzzrQI6FvIOYuKNIrASuJw=,tag:Iy/BgPTrPYmw05nB/Z8jdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upacrwymnmragd6phh5z2nfhew4jlf47cqvjnepxvauej7ufcd4scuqe7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaFhHUVB4cE1MTytVeno1
            dE1jSVFnZWJoZGJlZVd3YWFKdUtXc1FoQmhFCk5YRWRqLzRlTTZNVHRWU2NaMVVP
            eTZUQ1lzWEl5am5xejJOc1dpOWtmQk0KLS0tIC9LbjFMOGdxN1NnbzlSWGx4VjNk
            L1lTS3lObUhqL1htR1VVelpTS0U5WWsKBmJ1H2HLI+5RoUXAxIBhJvl5iROkE6Dz
            1Mq12Mki0GzYOWTqSre+Nk6hFVHaSi7952YEJ5GGyFFtuX3ThqWYPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T10:39:17Z"
    mac: ENC[AES256_GCM,data:s4+dtKQjm+pRPX2Uva07v+5v1H70lRa2NgLe0P/MjxeGPIjDnEzJ++JAql8MfuuqWLygpJwHvmHs29Kd5oj5xudn7VH7j5g/OAXmsQbyN0USuOaxu4gpSPo+/9cSVV/+L6TwNzrCipyKLqUZdffI8g+CsxmXKc+pTIf1RP9C95A=,iv:V4L9LMxmKuQnkf4r719WSZ4n0asVOuWQt7cG/6q3KGA=,tag:PXJsmYi6av+nFQvMjFLlBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
