apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:flQMVbUz1elEmZM71Qo/kQYN1UKWq77t9n8HmVyq3d2VX8dxuPjTBQ==,iv:6UlJjtgjBInVM/t2QNDSlHRjQeS7UTsGhwW8+j5K7Mc=,tag:seZ25e1YxqbdSYdWQxyJgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upacrwymnmragd6phh5z2nfhew4jlf47cqvjnepxvauej7ufcd4scuqe7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVlVJZlRjeW4yN1hCTzdk
            RWhIV2h1b1dmRkRwTjNCQ2poM0VzS1ROK2tvCno3cDltTWxVQnFROElxS3k0NWEv
            ZXJrZnJHZXJiSUd1eTlSWUY5M2djaDgKLS0tIGdzR3NxczhlZlhWUDZIanZoM3J1
            VS85Wko5NTVXRU5CbllBQ0tpN04zZGcKYrwzjSpa5jxgPARuwlB2kVi3X5/9pZ6j
            HlV9AshLzqUCqMaSv4DMJhIP3nxNmGTXEMJtLfd2DVxjQKo3CoSbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T10:48:59Z"
    mac: ENC[AES256_GCM,data:yz4T9DEFrh06/77QmkywG1grozI74hI5T2PRBKSLYh4i8p67VFRjpzu0IiY75ktzww9BP2HDYsONqKuY/YGpTMZMGcu0b4YYY5h8bSS6KnbZwpvu1sb5vA5gz66uN3r+9VApMHpVyspppBfmkXLf4uRCpx1WRGyQ4A6MvywXJtc=,iv:RysRIZoP90npAasOKmlBU60ijBHMRh3AmadceuLsy2Y=,tag:5pxrz9fJGY3ANyiS88ecqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
